repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: # arguments to configure black
        - --line-length=120
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
    -   id: flake8
        # E203 - ":" with whitespace before it
        # temporarily exclude specific files until refactoring is done
        args:
        - "--max-line-length=120"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        - "--ignore=E203,W503"
